/* 3840x2160: Modeline "3840x2160" 533.25 3840 3888 3920 4000 2160 2163 2168 2222 */
#define HSYNC_POL 0
#define VSYNC_POL 0
#define YPULSE (63+5)
#define XPULSE 32
#define YPIX 2160
#define XPIX 3840
#define VFREQ 60
#define DPI 96
#define CLOCK 533250
#define VERSION 1
#define REVISION 3
#define XOFFSET 48
#define YOFFSET (63+3)
#define XY_RATIO XY_RATIO_16_9
#define YBLANK 62
#define XBLANK 160
#define TIMING_NAME "3840x2160"
#include "edid.S"
