/* 3840x2160: Modeline "3840x2160" 712.75 3840 4160 4576 5312 2160 2163 2168 2237 -hsync +vsync */
#define HSYNC_POL 1
#define VSYNC_POL 1
#define YPULSE (63+5)
#define XPULSE 416
#define YPIX 2160
#define XPIX 3840
#define VFREQ 60
#define DPI 96
#define CLOCK 712750
#define VERSION 1
#define REVISION 3
#define XOFFSET 320
#define YOFFSET (63+3)
#define XY_RATIO XY_RATIO_16_9
#define YBLANK 77
#define XBLANK 1472
#define TIMING_NAME "3840x2160"
#include "edid.S"
